// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Item struct {
	ID     int64  `json:"id" gorm:"primaryKey"`
	Name   string `json:"name"`
	Cost   int    `json:"cost"`
	Seller string `json:"seller"`
}

type Order struct {
	ID        int64   `json:"id" gorm:"primaryKey"`
	Total     int     `json:"total"`
	Items     []*Item `json:"items" gorm:"foreignKey:ID"`
	Customer  string  `json:"customer"`
	OrderDate string  `json:"orderDate"`
}

type User struct {
	ID    int64  `json:"id" gorm:"primaryKey"`
	Name  string `json:"name"`
	Email string `json:"email"`
	Phone string `json:"phone"`
}

type NewItem struct {
	Name   string `json:"name"`
	Cost   int    `json:"cost"`
	Seller string `json:"seller"`
}

type NewOrder struct {
	Total     int        `json:"total"`
	Items     []*NewItem `json:"items"`
	Customer  string     `json:"Customer"`
	OrderDate string     `json:"orderDate"`
}

type NewUser struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	Phone string `json:"phone"`
}
